"""
Data loading utilities for the dashboard.
"""

import pandas as pd
import os


def load_results_data(results_path=None):
    """
    Load the model results CSV generated by analyze_results.py

    Args:
        results_path: Path to results CSV. If None, uses default location.

    Returns:
        pd.DataFrame: Results dataframe with datetime parsing
    """
    if results_path is None:
        results_path = os.path.join(
            os.path.dirname(__file__),
            "..",
            "..",
            "outputs",
            "results",
            "model_results_with_contributions.csv",
        )

    df = pd.read_csv(results_path)
    df["date"] = pd.to_datetime(df["date"])

    return df


def get_driver_columns(df):
    """
    Extract driver column names from the dataframe.

    Args:
        df: Results dataframe

    Returns:
        dict: {'original': [...], 'scaled': [...]}
    """
    driver_cols_original = [col for col in df.columns if col.startswith("driver_") and col.endswith("_original")]
    driver_cols_scaled = [col for col in df.columns if col.startswith("driver_") and col.endswith("_scaled")]

    return {"original": driver_cols_original, "scaled": driver_cols_scaled}


def get_feature_names_from_drivers(driver_cols):
    """
    Extract clean feature names from driver column names.

    Args:
        driver_cols: List of driver column names (e.g., ['driver_price_original', ...])

    Returns:
        list: Clean feature names (e.g., ['price', ...])
    """
    return [
        col.replace("driver_", "").replace("_original", "").replace("_scaled", "")
        for col in driver_cols
    ]


def get_hierarchy_columns():
    """
    Get hierarchy column names.

    Returns:
        list: Hierarchy column names
    """
    return ["region", "state", "segment", "brand", "pack"]
